# Generated by Django 4.1.3 on 2022-11-08 00:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=254)),
                ('Lastname', models.CharField(max_length=254)),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], max_length=5)),
                ('Date_of_Birth', models.DateField(max_length=254)),
                ('Email', models.EmailField(max_length=254)),
                ('Institute', models.CharField(max_length=254)),
                ('Region', models.CharField(max_length=254)),
                ('username', models.CharField(default='book', max_length=254)),
                ('password1', models.CharField(default='123', max_length=254)),
                ('password2', models.CharField(default='123', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=254)),
                ('Pages', models.CharField(max_length=254)),
                ('Edition', models.CharField(max_length=254)),
                ('Published_date', models.DateTimeField(auto_now=True)),
                ('Price', models.CharField(max_length=254)),
                ('Copies', models.CharField(max_length=254)),
                ('Poster', models.ImageField(default='avatar.jpg', upload_to='static/images')),
                ('Filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('Author', models.ForeignKey(default='book', on_delete=django.db.models.deletion.CASCADE, to='Brainfeeds.author')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is_admin')),
                ('is_author', models.BooleanField(default=False, verbose_name='Is_author')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Is_customer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Copies', models.IntegerField()),
                ('Cardnumber', models.IntegerField()),
                ('cardholder', models.CharField(max_length=254)),
                ('cvv', models.IntegerField()),
                ('Price', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Author', models.ForeignKey(default='book', on_delete=django.db.models.deletion.CASCADE, to='Brainfeeds.author')),
                ('Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brainfeeds.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brainfeeds.genre'),
        ),
    ]
