# Generated by Django 4.1.3 on 2022-11-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brainfeeds', '0003_contact_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Book_id',
            new_name='id',
        ),
    ]
