# Generated by Django 4.1.3 on 2022-11-17 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brainfeeds', '0005_alter_order_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
