# Generated by Django 4.1.3 on 2022-11-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brainfeeds', '0006_alter_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Institute',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
    ]
