# Generated by Django 4.1.3 on 2022-11-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brainfeeds', '0010_books_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
